name: Add Rules to Cloudflare Gateway
on:
  schedule:
    - cron: "10 20 * * *"
  workflow_dispatch:
jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
          check-latest: true
          go-version-file: 'go.mod'
          cache-dependency-path: go.sum

      - name: Build
        run: CGO_ENABLED=0 go build -ldflags '-s -w -buildid=' -trimpath

      - name: Run
        run: ./cloudflare_pihole
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 14 # Keep workflow runs from the last 14 days
